spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ug
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: ${app.timezone}
    hibernate:
      ddl-auto: create-drop
  application:
    name: Uniwersytet Gdanski

logging:
  level:
    root: INFO
    pl.ug: DEBUG
  file:
    name: logs/application.log

app:
  timezone: Europe/Warsaw